package ua.pimenova.model.database.dao.impl;

import org.apache.log4j.Logger;
import ua.pimenova.model.database.dao.FreightDao;
import ua.pimenova.model.database.dao.HikariCPDataSource;
import ua.pimenova.model.database.dao.constants.SqlQuery;
import ua.pimenova.model.database.dao.constants.SqlFields;
import ua.pimenova.model.database.entity.Freight;
import ua.pimenova.model.exception.DaoException;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Freight DAO class for database. Matches table 'freights' in database.
 *
 * @author Svetlana Pimenova
 * @version 1.0
 */
public class FreightDaoImpl implements FreightDao {
    private static FreightDaoImpl instance = null;
    private static final Logger LOGGER = Logger.getLogger(FreightDaoImpl.class);
    private FreightDaoImpl() {}

    public static synchronized FreightDaoImpl getInstance() {
        if(instance == null) {
            instance = new FreightDaoImpl();
        }
        return instance;
    }

    /**
     * Obtains instance of Freight from database by id
     *
     * @param id - value of id field in database
     * @return - instance of Freight
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public Freight getByID(int id) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.FreightQuery.SELECT_FREIGHT_BY_ID)) {
            statement.setInt(1, id);
            ResultSet resultSet = statement.executeQuery();
            if(resultSet != null) {
                return getFreight(resultSet);
            }
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return null;
    }

    private Freight getFreight(ResultSet resultSet) throws SQLException {
        Freight freight = null;
        while (resultSet.next()) {
            freight = new Freight();
            freight.setId(resultSet.getInt(SqlFields.ID));
            freight.setWeight(resultSet.getDouble(SqlFields.WEIGHT));
            freight.setLength(resultSet.getDouble(SqlFields.LENGTH));
            freight.setWidth(resultSet.getDouble(SqlFields.WIDTH));
            freight.setHeight(resultSet.getDouble(SqlFields.HEIGHT));
            freight.setEstimatedCost(resultSet.getInt(SqlFields.ESTIMATED_COST));
            freight.setType(Freight.FreightType.valueOf(resultSet.getString(SqlFields.FREIGHT_TYPE_NAME).toUpperCase()));
        }
        return freight;
    }

    /**
     * Obtains list of all freights from database
     * @return - list of all freights
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public List<Freight> getAll() throws DaoException {
        List<Freight> freights = new ArrayList<>();
        try(Connection connection = HikariCPDataSource.getConnection();
            Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery(SqlQuery.FreightQuery.SELECT_ALL_FREIGHTS);
            freights = getListOfFreights(freights, resultSet);
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return freights;
    }

    /**
     * Inserts new freight in database
     * @param freight - id will be generated by database. All fields should be not null
     * @return - instance of Freight with generated id
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public Freight create(Freight freight) throws DaoException {
        try (Connection connection = HikariCPDataSource.getConnection();
             PreparedStatement statement = connection.prepareStatement(SqlQuery.FreightQuery.ADD_FREIGHT, Statement.RETURN_GENERATED_KEYS)){
            statement.setDouble(1, freight.getWeight());
            statement.setDouble(2, freight.getLength());
            statement.setDouble(3, freight.getWidth());
            statement.setDouble(4, freight.getHeight());
            statement.setInt(5, freight.getEstimatedCost());
            statement.setInt(6, freight.getType().getId());
            statement.executeUpdate();
            ResultSet resultSet = statement.getGeneratedKeys();
            while (resultSet.next()) {
                freight.setId(resultSet.getInt(1));
            }
            return freight;
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
    }

    /**
     * Updates freight
     * @param freight - all fields should be not null
     * @return - boolean value
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public boolean update(Freight freight) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.FreightQuery.UPDATE_FREIGHT)) {
            statement.setDouble(1, freight.getWeight());
            statement.setDouble(2, freight.getLength());
            statement.setDouble(3, freight.getWidth());
            statement.setDouble(4, freight.getHeight());
            statement.setInt(5, freight.getEstimatedCost());
            statement.setInt(6, freight.getType().getId());
            statement.setInt(7, freight.getId());
            return  statement.executeUpdate() > 0;
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
    }

    /**
     * Deletes freight from database
     * @param freight - freight, that must be deleted
     * @return - boolean value
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public boolean delete(Freight freight) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.FreightQuery.DELETE_FREIGHT)) {
            statement.setInt(1, freight.getId());
            return  statement.executeUpdate() > 0;
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
    }

    /**
     * Obtains list of all freights from database by freight type
     * @param type - can be goods/glass/compact
     * @return - list of freights
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public List<Freight> getAllFreightsByType(Freight.FreightType type) throws DaoException {
        List<Freight> freights = new ArrayList<>();
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.FreightQuery.SELECT_FREIGHTS_BY_TYPE)) {
            statement.setString(1, type.toString().toLowerCase());
            ResultSet resultSet = statement.executeQuery();
            freights = getListOfFreights(freights, resultSet);
        } catch(SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return freights;
    }

    private List<Freight> getListOfFreights(List<Freight> freights, ResultSet resultSet) throws SQLException {
        while (resultSet.next()) {
            int id  = resultSet.getInt(SqlFields.ID);
            double weight = resultSet.getDouble(SqlFields.WEIGHT);
            double length = resultSet.getDouble(SqlFields.LENGTH);
            double width = resultSet.getDouble(SqlFields.WIDTH);
            double height = resultSet.getDouble(SqlFields.HEIGHT);
            int estimatedCost = resultSet.getInt(SqlFields.ESTIMATED_COST);
            Freight.FreightType type = Freight.FreightType.valueOf(resultSet.getString(SqlFields.FREIGHT_TYPE_NAME).toUpperCase());
            freights.add(new Freight(id, weight, length, width, height, estimatedCost, type));
        }
        return freights;
    }
}
