package ua.pimenova.model.database.dao.impl;

import org.apache.log4j.Logger;
import ua.pimenova.model.database.dao.HikariCPDataSource;
import ua.pimenova.model.database.dao.constants.SqlFields;
import ua.pimenova.model.database.dao.constants.SqlQuery;
import ua.pimenova.model.database.dao.UserDao;
import ua.pimenova.model.database.entity.User;
import ua.pimenova.model.exception.DaoException;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * User DAO class for database. Matches table 'users' in database.
 *
 * @author Svetlana Pimenova
 * @version 1.0
 */
public class UserDaoImpl implements UserDao {
    private static UserDaoImpl instance = null;
    private static final Logger LOGGER = Logger.getLogger(UserDaoImpl.class);
    private UserDaoImpl() {
    }

    public static synchronized UserDaoImpl getInstance() {
        if(instance == null) {
            instance = new UserDaoImpl();
        }
        return instance;
    }

    /**
     * Obtains instance of User from database by id
     *
     * @param id - value of id field in database
     * @return - instance of User
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public User getByID(int id) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.SELECT_USER_BY_ID)) {
            statement.setInt(1, id);
            ResultSet resultSet = statement.executeQuery();
            if(resultSet != null) {
                return getUser(resultSet);
            }
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return null;
    }
    private User getUser(ResultSet resultSet) throws SQLException {
        User user = null;
        while (resultSet.next()) {
            user = new User();
            user.setId(resultSet.getInt(SqlFields.ID));
            user.setPassword(resultSet.getString(SqlFields.PASSWORD));
            user.setFirstname(resultSet.getString(SqlFields.FIRSTNAME));
            user.setLastname(resultSet.getString(SqlFields.LASTNAME));
            user.setPhone(resultSet.getString(SqlFields.PHONE));
            user.setEmail(resultSet.getString(SqlFields.EMAIL));
            user.setAccount(resultSet.getInt(SqlFields.ACCOUNT));
            user.setRole(User.Role.valueOf(resultSet.getString(SqlFields.ROLE)));
            user.setCity(resultSet.getString(SqlFields.CITY));
            user.setStreet(resultSet.getString(SqlFields.STREET));
            user.setPostalCode(resultSet.getString(SqlFields.POSTAL_CODE));
        }
        return user;
    }

    /**
     * Obtains list of all users from database
     * @return - list of all users
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public List<User> getAll() throws DaoException {
        List<User> users = new ArrayList<>();
        try(Connection connection = HikariCPDataSource.getConnection();
            Statement statement = connection.createStatement()) {
            ResultSet resultSet = statement.executeQuery(SqlQuery.UsersQuery.SELECT_ALL_USERS);
            users = getListOfUsers(users, resultSet);
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return users;
    }

    private List<User> getListOfUsers(List<User> users, ResultSet resultSet) throws SQLException {
        while (resultSet.next()) {
            int id  = resultSet.getInt(SqlFields.ID);
            String password = resultSet.getString(SqlFields.PASSWORD);
            String firstName = resultSet.getString(SqlFields.FIRSTNAME);
            String lastName = resultSet.getString(SqlFields.LASTNAME);
            String phone = resultSet.getString(SqlFields.PHONE);
            String email = resultSet.getString(SqlFields.EMAIL);
            int account  = resultSet.getInt(SqlFields.ACCOUNT);
            User.Role role = User.Role.valueOf(resultSet.getString(SqlFields.ROLE));
            String city = resultSet.getString(SqlFields.CITY);
            String street = resultSet.getString(SqlFields.STREET);
            String postalCode = resultSet.getString(SqlFields.POSTAL_CODE);
            users.add(new User(id, password, firstName, lastName, phone, email, account, role, city, street, postalCode));
        }
        return users;
    }

    /**
     * Inserts new user in database
     * @param user - id will be generated by database. All fields should be not null
     * @return - instance of User with generated id
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public User create(User user) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.ADD_USER, Statement.RETURN_GENERATED_KEYS)) {
            statement.setString(1, user.getPassword());
            statement.setString(2, user.getFirstname());
            statement.setString(3, user.getLastname());
            statement.setString(4, user.getPhone());
            statement.setString(5, user.getEmail());
            statement.setInt(6, user.getAccount());
            statement.setString(7, user.getRole().name());
            statement.setString(8, user.getCity());
            statement.setString(9, user.getStreet());
            statement.setString(10, user.getPostalCode());
            statement.executeUpdate();
            ResultSet resultSet = statement.getGeneratedKeys();
            while (resultSet.next()) {
                user.setId(resultSet.getInt(1));
            }
            return user;
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
    }

    /**
     * Updates user
     * @param user - all fields should be not null
     * @return - boolean value
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public boolean update(User user) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.UPDATE_USER)) {
            statement.setString(1, user.getFirstname());
            statement.setString(2, user.getLastname());
            statement.setString(3, user.getPhone());
            statement.setString(4, user.getEmail());
            statement.setInt(5, user.getAccount());
            statement.setString(6, user.getRole().name());
            statement.setString(7, user.getCity());
            statement.setString(8, user.getStreet());
            statement.setString(9, user.getPostalCode());
            statement.setInt(10, user.getId());
            return  statement.executeUpdate() > 0;
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
    }

    /**
     * Updates specific field of user
     * @param user - user, which password must be updated
     * @return - boolean value
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public boolean updatePassword(User user) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.UPDATE_USER_PASSWORD)) {
            statement.setString(1, user.getPassword());
            statement.setInt(2, user.getId());
            return  statement.executeUpdate() > 0;
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
    }

    /**
     * Deletes user from database
     * @param user - user, that must be deleted
     * @return - boolean value
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public boolean delete(User user) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.DELETE_USER)) {
            statement.setInt(1, user.getId());
            return  statement.executeUpdate() > 0;
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
    }

    /**
     * Obtains instance of User from database by phone
     * @param phone - user phone to find
     * @return - instance of User
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public User getByPhone(String phone) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.SELECT_USER_BY_PHONE)) {
            statement.setString(1, phone);
            ResultSet resultSet = statement.executeQuery();
            if(resultSet != null) {
                return getUser(resultSet);
            }
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return null;
    }

    /**
     * Obtains instance of User from database by email
     * @param email - user phone to find
     * @return - instance of User
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public User getByEmail(String email) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.SELECT_USER_BY_EMAIL)) {
            statement.setString(1, email);
            ResultSet resultSet = statement.executeQuery();
            if(resultSet != null) {
                return getUser(resultSet);
            }
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return null;
    }

    /**
     * Obtains instance of User from database by email and password
     * @param email - user email to find
     * @param password - user password to find
     * @return - instance of User
     * @throws DaoException - is wrapper for SQLException
     */
    @Override
    public User getUserByEmailAndPassword(String email, String password) throws DaoException {
        try(Connection connection = HikariCPDataSource.getConnection();
            PreparedStatement statement = connection.prepareStatement(SqlQuery.UsersQuery.SELECT_USER_BY_EMAIL_AND_PASSWORD)) {
            statement.setString(1, email);
            statement.setString(2, password);
            ResultSet resultSet = statement.executeQuery();
            if(resultSet != null) {
                return getUser(resultSet);
            }
        } catch (SQLException e) {
            LOGGER.error(e.getMessage());
            throw new DaoException(e);
        }
        return null;
    }
}
